

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network


  app:
    build: .
    ports:
      - "${PORT}:3000"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
