FROM koyeb/docker-compose

COPY . /app


# Copy your Docker Compose files into the container
 COPY docker-compose.yaml ./
# COPY .env ./

# # Install any dependencies (if needed)
# # RUN apt-get update && apt-get install -y some-magical-package

# # The spell to invoke Docker Compose
 CMD ["docker-compose", "up"]