# render.yaml

services:
  - type: web
    name: spring-boot-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile  # Make sure you have a Dockerfile in your project root
    buildCommand: ./mvnw package
    startCommand: java -jar target/deploy_test-0.0.1-SNAPSHOT.jar
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_REDIS_HOST
        value: redis
      - key: SPRING_REDIS_PORT
        value: "6379"
    ports:
      - 3000

  - type: redis
    name: redis-service
    plan: free
    dockerImage: redis:latest
    disk:
      name: redis-disk
      mountPath: /data
      sizeGB: 1
